# 1.算数平均值法求权重
步骤：
1. 判断矩阵按照列求和，得到新矩阵a_axis_0_sum
2. 把判断矩阵中的每一个数除以列和，得到新的矩阵b
3. 计算新矩阵b的行和，得到新矩阵b_axis_1_sum
4. 把b_axis_1_sum每一个值除以总和，获得权重
5. 求解最大特征值
6. 计算C_R判断矩阵的一致性，如果验证通过就输出结果

In [1]:
import numpy as np
#  建立平均随机一致性指标R.I
RI_dict = {1: 0, 2: 0, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45, 10: 1.49}
RI_dict

{1: 0,
 2: 0,
 3: 0.58,
 4: 0.9,
 5: 1.12,
 6: 1.24,
 7: 1.32,
 8: 1.41,
 9: 1.45,
 10: 1.49}

In [3]:
a = np.array([[1, 1 / 3, 1 / 8], [3, 1, 1 / 3], [8, 3, 1]])
a

array([[1.        , 0.33333333, 0.125     ],
       [3.        , 1.        , 0.33333333],
       [8.        , 3.        , 1.        ]])

In [4]:
print(a.sum(axis=0))## 我们首先验证了一下按照列进行求和的可能性

array([12.        ,  4.33333333,  1.45833333])

In [5]:
sum(a)

array([12.        ,  4.33333333,  1.45833333])

In [ ]:
def get_w(array):
    # 1、计算出阶数 看这个数组是几维的 也就是后面对应字典查询！
    row = array.shape[0]  
    # 2、按列求和
    a_axis_0_sum = array.sum(axis=0) 
    # 3、得到新的矩阵b 就是把每一个数都除以列和 
    b = array / a_axis_0_sum  
    # 4、计算新矩阵b行和
    b_axis_1_sum = b.sum(axis=1)  
    # 5、将b_axis_1_sum每一个值除以总和
    W = b_axis_1_sum / sum(b_axis_1_sum)
    # 6、将原始矩阵乘以W
    a_W = np.dot(array, W)
    # 7、求解最大特征值 
    lambda_max = 0
    for i in range(len(a_W)):
        lambda_max += (a_W[i] / W[i])
    lambda_max = lambda_max / len(a_W)      #求最大特征值
    # 8、检验判断矩阵的一致性
    C_I = (lambda_max - row) / (row - 1)
    R_I = RI_dict[row] 
    C_R = C_I / R_I 
    if C_R < 0.1:
        print('矩阵 %s 一致性检验通过' % (array))
        print('判断矩阵对应的指标的权重为：%s' % W)
        print('判断矩阵对应的最大特征值为 %.2f' % lambda_max)
        print('大功告成！！！')
        return W
    else:
        print('矩阵 %s 一致性检验未通过，需要重新进行调整判断矩阵' % (array))
    
def main(array):
    if type(array) is np.ndarray:
        return get_w(array)
    else:
        print('请输入正确的numpy对象')