In [2]:
## 1.导入Numpy 
import numpy as np

In [3]:
## 2.向量相加
def numpysum(n):
    a = np.arange(n)**2
    b = np.arange(n)**3
    c = a+b
    return a,b,c
print(numpysum(20))

(array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361]), array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859], dtype=int32), array([   0,    2,   12,   36,   80,  150,  252,  392,  576,  810, 1100,
       1452, 1872, 2366, 2940, 3600, 4352, 5202, 6156, 7220]))


In [6]:
## 3.Numpy数组
a = np.arange(5)
print(type(a)) # 查看a的类型
print(a.dtype) # 查看类型-查看的是array元素的类型
print(a.shape) # 查看维度
a

<class 'numpy.ndarray'>
int32
(5,)


array([0, 1, 2, 3, 4])

In [9]:
# 创建多维数组
m = np.array([np.arange(2),np.arange(2),np.arange(2)])
print(m)
print(m.dtype)
print(m.shape)

[[0 1]
 [0 1]
 [0 1]]
int32
(3, 2)


In [12]:
# 创建0数组或者空数组
print(np.zeros(10)) # 创建全是0的数组
print(np.zeros((3,6))) # 创建全是0的多维数组
print(np.empty((2,3,2))) # 创建随机值的数组
print(np.arange(15)) # 创建普通的数组

(10,)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[1.08648792e-311 2.81617418e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.06099790e-312 5.64233733e-067]]

 [[5.02917000e-091 1.08689741e-071]
  [6.59153282e-043 8.24558904e-043]
  [6.48224659e+170 4.93432906e+257]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
# 选取数组元素
a = np.array([[1,2],[3,4]]) # 生成二维数组，
print(a)
print(a[0,0])
print(a[0,1])
print(a[1,0])
print(a[1,1])
print(a[0])

[[1 2]
 [3 4]]
1
2
3
4
[1 2]


In [20]:
## 4.Numpy数据类型
print(np.float64(42)) # 64位浮点数
print(np.int8(42.0)) # 8位整数
print(np.bool(42))  # 布尔型
print(np.float(True))
print(np.float(False))

42.0
42
True
1.0
0.0


C:\Users\zyy\AppData\Local\Temp\ipykernel_25936\159361072.py:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.bool(42))  # 布尔型
C:\Users\zyy\AppData\Local\Temp\ipykernel_25936\159361072.py:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.float(True))
C:\Users\zyy\AppData\Local\Temp\ipykernel_25936\159361072.py:6: DeprecationWa

In [25]:
## 5.数据类型转换
arr = np.array([1,2,3,4,5]) # 生成一维数组
print(a.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.11])
print(arr)
print(arr.astype(np.int32))#将浮点数转换为32位整数类型

int32
float64
[ 3.7  -1.2  -2.6   0.5  12.9  10.11]
[ 3 -1 -2  0 12 10]


In [29]:
## 6.创建自定义数据类型
t = np.dtype([('name',np.str_,40),('numitems',np.int32),('price',np.float32)])
print(t)
itemz = np.array([('Meaning of life',42,3.14),('Butter',13,2.72)],dtype=t)
print(itemz)
print(itemz[0][0])

[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')]
[('Meaning of life', 42, 3.14) ('Butter', 13, 2.72)]
Meaning of life


In [31]:
## 7.数组与标量的运算
arr = np.array([[1,2,3],[4,5,6]])
print(arr)#输出数组
print(arr*arr)#数组平方
print(arr**2)
print(arr-arr)#数组相减
print(1/arr)#数组倒数
print(arr**0.5)#数组开根号

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [34]:
## 8.一维数组的索引和切片
a = np.arange(9)
print(a)
print(a[:7:2])#选取（0，6），隔两个选取
print(a[3:7])#选取（3，6）
print(a[::-1])#从末尾到头逐一选取
print(a[-1])

s = slice(3,7,2)#另一种切片方式
print(a[s])

s=slice(None, None, -1)#从末尾到头逐一选取
print(a[s])

[0 1 2 3 4 5 6 7 8]
[0 2 4 6]
[3 4 5 6]
[8 7 6 5 4 3 2 1 0]
8
[3 5]
[8 7 6 5 4 3 2 1 0]


In [36]:
## 9.多维数组的索引与切片
b= np.arange(24).reshape(2,3,4)#创建一个三维数组
print(b.shape)#查看维度
print(b)

print(b[0,0,0])#获得0层0行0列的数据
print(b[:,0,0])#获得每一层0行0列的数据
print(b[0])#获得0层的数据
print(b[0,:,:])#获得0层的数据
print(b[0,...])#获得0层的数据
print(b[0,1])#获得0层1行的数据
print(b[0,1,::2])#获得0层1行每一列的数据，逐2选取

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
0
[ 0 12]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
[4 6]


In [39]:
## 10.布尔型索引
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])#布尔型数组
data=np.random.randn(7,4)#生成二维的正态分布数据
print(names)
print(data)
print(names == 'Bob')#查看names数组中的每一个元素是否为Bob，返回一个布尔型数组
print(data[names == 'Bob'])#显示数组中为True的行
print(data[names == 'Bob',2:])
print(names != 'Bob')#查看names数组中的每一个元素是否为Bob，返回一个布尔型数组
mask = (names == 'Bob') | (names == 'Will')#查看names数组中的每一个元素是否为Bob或Will，返回一个布尔型数组
print(mask)
print(data[mask])

data[data < 0] = 0#将数组中小于0的数修改为0
print(data)

data[names != 'Joe'] = 7#将数组中对应Joe的数据修改为7
print(data)


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.48669892 -0.74303893 -0.51534483 -1.39172196]
 [-0.014419    0.90210859 -0.25657407 -0.97040167]
 [-1.07038954  0.85138702  0.19612623 -1.13383257]
 [-0.23000766  1.35733018  1.2376333  -0.17897652]
 [ 0.04684496  0.95076155 -0.79327814 -0.77349091]
 [-1.8807609   0.56517609  0.88570096  0.35190682]
 [ 0.14216949 -1.31221391  1.44597564 -1.00575968]]
[ True False False  True False False False]
[[-0.48669892 -0.74303893 -0.51534483 -1.39172196]
 [-0.23000766  1.35733018  1.2376333  -0.17897652]]
[[-0.51534483 -1.39172196]
 [ 1.2376333  -0.17897652]]
[False  True  True False  True  True  True]
[ True False  True  True  True False False]
[[-0.48669892 -0.74303893 -0.51534483 -1.39172196]
 [-1.07038954  0.85138702  0.19612623 -1.13383257]
 [-0.23000766  1.35733018  1.2376333  -0.17897652]
 [ 0.04684496  0.95076155 -0.79327814 -0.77349091]]
[[0.         0.         0.         0.        ]
 [0.         0.90210859 0.         0.        ]
 [0.   