In [2]:
# from selectors import EpollSelector
from tkinter.tix import MAIN
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import Normalizer
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [6]:
sl = True
df = pd.read_csv("HR.csv")
    
    # 1.find label
    
df = df.drop("left",axis=1)
    
    # 2.clean the data
df.dropna(subset=["satisfaction_level","last_evaluation"])
df = df[df["satisfaction_level"]<=1][df["salary"]!="nme"]
    
    # 3.feature selection
    
    # 4.feature processing
scaler_lst = [sl]
column_lst = ["satisfaction_level"]



In [7]:
scaler_lst

[True]

In [8]:
len(scaler_lst)

1

In [24]:
for i in range(len(scaler_lst)):
    if not scaler_lst[i]:
        df[column_lst[i]] =\
            MinMaxScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]
    else:
        df[column_lst[i]]=\
            StandardScaler().fit_transform(df[column_lst[0]].values.reshape(-1,1)).reshape(1,-1)[0]
            
df

satisfaction_level  last_evaluation  number_project  \
0               -0.936495             0.53               2   
1                0.752814             0.86               5   
2               -2.022479             0.88               7   
3                0.431041             0.87               5   
4               -0.976716             0.52               2   
...                   ...              ...             ...   
14994           -0.856051             0.57               2   
14995           -0.976716             0.48               2   
14996           -0.976716             0.53               2   
14997           -2.022479             0.96               6   
14998           -0.976716             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  \
0                       157                   3              0   
1                       262                   6              0   
2                       272                   4              0   
3                       223                   5              0   
4                       159                   3              0   
...                     ...                 ...            ...   
14994                   151                   3              0   
14995                   160                   3              0   
14996                   143                   3              0   
14997                   280                   4              0   
14998                   158                   3              0   

       promotion_last_5years    sales  salary  
0                          0    sales     low  
1                          0    sales  medium  
2                          0    sales  medium  
3                          0    sales     low  
4                          0    sales     low  
...                      ...      ...     ...  
14994                      0  support     low  
14995                      0  support     low  
14996                      0  support     low  
14997                      0  support     low  
14998                      0  support     low  

[14999 rows x 9 columns]

In [26]:
StandardScaler().fit_transform(df[column_lst[0]].values.reshape(-1,1)).reshape(1,-1)

array([[-0.93649469,  0.75281433, -2.02247906, ..., -0.97671633,
        -2.02247906, -0.97671633]])

In [27]:
StandardScaler().fit_transform(df[column_lst[0]].values.reshape(-1,1)).reshape(1,-1)[0]

array([-0.93649469,  0.75281433, -2.02247906, ..., -0.97671633,
       -2.02247906, -0.97671633])

In [28]:
df[column_lst[0]].values.reshape(-1,1)

array([[-0.93649469],
       [ 0.75281433],
       [-2.02247906],
       ...,
       [-0.97671633],
       [-2.02247906],
       [-0.97671633]])

In [29]:
df[column_lst[0]].values

array([-0.93649469,  0.75281433, -2.02247906, ..., -0.97671633,
       -2.02247906, -0.97671633])