In [1]:
## 特征选择
import pandas as pd
import numpy as np
import scipy.stats as ss

In [8]:
df = pd.DataFrame({"A":ss.norm.rvs(size=10),"B":ss.norm.rvs(size=10),"C":ss.norm.rvs(size=10),"D":np.random.randint(low=0,high=2,size=10)})

In [9]:
df


A         B         C  D
0  1.239219 -0.825722  1.110227  1
1  1.256356 -0.469808 -1.865242  1
2 -0.404472  0.533275 -0.331897  1
3  0.477849  1.093456  0.564481  1
4  1.502098 -0.662746  0.154725  0
5  2.136759  0.475394  1.428132  0
6 -0.095537  1.506293 -0.768372  0
7 -1.454003 -0.680083  1.074438  0
8 -0.938932  1.616372  0.388531  1
9 -1.202257  0.770339  0.896757  1

In [10]:
from sklearn.svm import SVR 
from sklearn.tree import DecisionTreeRegressor

In [18]:
X = df.loc[:,["A","B","C"]]
X

A         B         C
0  1.239219 -0.825722  1.110227
1  1.256356 -0.469808 -1.865242
2 -0.404472  0.533275 -0.331897
3  0.477849  1.093456  0.564481
4  1.502098 -0.662746  0.154725
5  2.136759  0.475394  1.428132
6 -0.095537  1.506293 -0.768372
7 -1.454003 -0.680083  1.074438
8 -0.938932  1.616372  0.388531
9 -1.202257  0.770339  0.896757

In [19]:
Y = df.loc[:,["D"]]
Y

D
0  1
1  1
2  1
3  1
4  0
5  0
6  0
7  0
8  1
9  1

In [20]:
from sklearn.feature_selection import SelectKBest,RFE,SelectFromModel

In [26]:
## 过滤思想,去掉相关性差的特征
skb = SelectKBest(k=2)
skb.fit(X,Y)
skb.transform(X)

d:\Download\python\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[ 1.23921914,  1.11022736],
       [ 1.25635576, -1.86524204],
       [-0.40447195, -0.33189702],
       [ 0.47784879,  0.56448094],
       [ 1.50209817,  0.15472463],
       [ 2.13675883,  1.42813195],
       [-0.09553683, -0.76837211],
       [-1.45400346,  1.0744381 ],
       [-0.93893151,  0.38853123],
       [-1.20225664,  0.89675735]])

In [27]:
## 包裹思想，构成简单模型，根据系数去掉弱特征
#estimator=SVR(kernel="linear")线性回归器  特征选择
#n_features_to_select=2,就是最终要选择几个特征
#step=1，每迭代一次，要去掉一个特征
rfe=RFE(estimator=SVR(kernel="linear"),n_features_to_select=2,step=1)
rfe.fit_transform(X,Y)

d:\Download\python\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
d:\Download\python\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[-0.82572208,  1.11022736],
       [-0.46980788, -1.86524204],
       [ 0.53327491, -0.33189702],
       [ 1.09345629,  0.56448094],
       [-0.66274606,  0.15472463],
       [ 0.47539389,  1.42813195],
       [ 1.50629317, -0.76837211],
       [-0.68008301,  1.0744381 ],
       [ 1.61637168,  0.38853123],
       [ 0.77033878,  0.89675735]])

In [28]:
## 嵌入思想，一般利用回归的方法
#SelectFromModel（）必须要有feature_importances和coef_这两个参数才能用
#estimator=DecisionTreeRegressor()特征选择
#threshold=0.1  重要性因子，低于0.1就会被去掉
sfm=SelectFromModel(estimator=DecisionTreeRegressor(),threshold=0.1)
sfm.fit_transform(X,Y)


array([[ 1.23921914, -0.82572208],
       [ 1.25635576, -0.46980788],
       [-0.40447195,  0.53327491],
       [ 0.47784879,  1.09345629],
       [ 1.50209817, -0.66274606],
       [ 2.13675883,  0.47539389],
       [-0.09553683,  1.50629317],
       [-1.45400346, -0.68008301],
       [-0.93893151,  1.61637168],
       [-1.20225664,  0.77033878]])