In [1]:
import pandas as pd
import numpy as np

In [2]:
lst = [6,8,10,15,16,24,25,40,67]

In [3]:
pd.qcut(lst,q=3)

[(5.999, 13.333], (5.999, 13.333], (5.999, 13.333], (13.333, 24.333], (13.333, 24.333], (13.333, 24.333], (24.333, 67.0], (24.333, 67.0], (24.333, 67.0]]
Categories (3, interval[float64, right]): [(5.999, 13.333] < (13.333, 24.333] < (24.333, 67.0]]

In [5]:
pd.qcut(lst,q=3,labels=["low","median","high"])

['low', 'low', 'low', 'median', 'median', 'median', 'high', 'high', 'high']
Categories (3, object): ['low' < 'median' < 'high']

In [6]:
pd.cut(lst,bins=3)

[(5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (26.333, 46.667], (46.667, 67.0]]
Categories (3, interval[float64, right]): [(5.939, 26.333] < (26.333, 46.667] < (46.667, 67.0]]

In [8]:
pd.cut(lst,bins=3,labels= ["low","median","high"])

['low', 'low', 'low', 'low', 'low', 'low', 'low', 'median', 'high']
Categories (3, object): ['low' < 'median' < 'high']

In [20]:
#导入模块
from sklearn.preprocessing import MinMaxScaler,StandardScaler
MinMaxScaler().fit_transform(np.array([1,4,10,15,21]).reshape(-1,1))
    

array([[0.  ],
       [0.15],
       [0.45],
       [0.7 ],
       [1.  ]])

In [17]:
StandardScaler().fit_transform(np.array([1,1,0,0,0,0,0,0]).reshape(-1,1))

array([[ 1.73205081],
       [ 1.73205081],
       [-0.57735027],
       [-0.57735027],
       [-0.57735027],
       [-0.57735027],
       [-0.57735027],
       [-0.57735027]])

In [21]:
# #特征选取
#     #sl,le,npr,amh,tsc,wa,pl5为False:采用归一化MinMaxScaler()算法，为True,采用标准化StandardScaler()算法
#     #特征处理
#     scaler_lst=[sl,le,npr,amh,tsc,wa,pl5]
#     column_lst=["satisfaction_level","last_evaluation","number_project",\
#                 "average_monthly_hours","time_spend_company","Work_accident",\
#                 "promotion_last_5years"]
#     for i in range(len(scaler_lst)):
#         if not scaler_lst[i]:
#             df[column_lst[i]]=\
#             MinMaxScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]
#         else:
#             df[column_lst[i]]=\
#             StandardScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]


In [22]:
## labelencoder
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [23]:
LabelEncoder().fit_transform(np.array(["Down","Up","Up","Down"])).reshape(-1,1)


array([[0],
       [1],
       [1],
       [0]], dtype=int64)

In [25]:
LabelEncoder().fit_transform(np.array(["Low","Median","High","Low"])).reshape(-1,1)


array([[1],
       [2],
       [0],
       [1]], dtype=int64)

In [29]:
lb_encoder = LabelEncoder()
lb_tran_f = lb_encoder.fit_transform(np.array(["Red","Yellow","Blue","Green"]))
lb_tran_f

array([2, 3, 0, 1], dtype=int64)

In [40]:
oht_encoder = OneHotEncoder().fit(lb_tran_f.reshape(-1,1))
oht_encoder.transform(lb_encoder.transform(np.array(["Yellow","Blue","Green","Green","Red"])).reshape(-1,1)).toarray