In [2]:
## 读取csv表中的数据
# 原文是excel表中的数据
# def read(file):
#     wb = xlrd.open_workbook(filename=file)#打开文件
#     sheet = wb.sheet_by_index(0)#通过索引获取表格
#     rows = sheet.nrows # 获取行数
#     all_content = []        #存放读取的数据
#     for j in range(1, 5):       #取第1~第4列对的数据
#         temp = []
#         for i in range(1,rows) :
#             cell = sheet.cell_value(i, j)   #获取数据 
#             temp.append(cell)           
#         all_content.append(temp)    #按列添加到结果集中
#         temp = []
#     return np.array(all_content)
import pandas as pd
import numpy as np
df = pd.read_csv("HR.csv")
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years    sales  salary  
0                          0    sales     low  
1                          0    sales  medium  
2                          0    sales  medium  
3                          0    sales     low  
4                          0    sales     low  
...                      ...      ...     ...  
14994                      0  support     low  
14995                      0  support     low  
14996                      0  support     low  
14997                      0  support     low  
14998                      0  support     low  

[14999 rows x 10 columns]

In [4]:
df_10 = df.head(10)
df_10

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   
5                0.41             0.50               2                   153   
6                0.10             0.77               6                   247   
7                0.92             0.85               5                   259   
8                0.89             1.00               5                   224   
9                0.42             0.53               2                   142   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   
5                   3              0     1                      0  sales   
6                   4              0     1                      0  sales   
7                   5              0     1                      0  sales   
8                   5              0     1                      0  sales   
9                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low  
5     low  
6     low  
7     low  
8     low  
9     low

In [22]:
df_res = df_10[["satisfaction_level","last_evaluation","number_project","left"]]
df_res

satisfaction_level  last_evaluation  number_project  left
0                0.38             0.53               2     1
1                0.80             0.86               5     1
2                0.11             0.88               7     1
3                0.72             0.87               5     1
4                0.37             0.52               2     1
5                0.41             0.50               2     1
6                0.10             0.77               6     1
7                0.92             0.85               5     1
8                0.89             1.00               5     1
9                0.42             0.53               2     1

In [5]:
# 我们可以看到satisfaction_level 是极大值指标，number_project 
# 是极小值指标，我们需要把不同的指标转化为极大值指标
#极小型指标 -> 极大型指标
def dataDirection_1(datas):         
		return np.max(datas)-datas     #套公式

#中间型指标 -> 极大型指标
def dataDirection_2(datas, x_best):
    temp_datas = datas - x_best
    M = np.max(abs(temp_datas))
    answer_datas = 1 - abs(datas - x_best) / M     #套公式
    return answer_datas
    
#区间型指标 -> 极大型指标
def dataDirection_3(datas, x_min, x_max):
    M = max(x_min - np.min(datas), np.max(datas) - x_max)
    answer_list = []
    for i in datas:
        if(i < x_min):
            answer_list.append(1 - (x_min-i) /M)      #套公式
        elif( x_min <= i <= x_max):
            answer_list.append(1)
        else:
            answer_list.append(1 - (i - x_max)/M)
    return np.array(answer_list)   


In [13]:
a = np.array([[1,2,5], [1/2,1,2], [1/5,1/2,1]])
a

array([[1. , 2. , 5. ],
       [0.5, 1. , 2. ],
       [0.2, 0.5, 1. ]])

In [8]:
pow(a,2)

array([[ 1.  ,  4.  , 25.  ],
       [ 0.25,  1.  ,  4.  ],
       [ 0.04,  0.25,  1.  ]])

In [12]:
np.sum(a,axis=1)

array([8. , 3.5, 1.7])

In [15]:
np.power(a,0.5)

array([[1.        , 1.41421356, 2.23606798],
       [0.70710678, 1.        , 1.41421356],
       [0.4472136 , 0.70710678, 1.        ]])

In [17]:
pow(a,0.5)
## 可以看到，pow 和np.power函数是大致相同的函数

array([[1.        , 1.41421356, 2.23606798],
       [0.70710678, 1.        , 1.41421356],
       [0.4472136 , 0.70710678, 1.        ]])

In [19]:
a.size

9

In [20]:
## 随后我们随后对于我们的正向化矩阵进行标准化调整
def temp2(datas):
    K = np.power(np.sum(pow(datas,2),axis =1),0.5)
    for i in range(0,K.size):
        for j in range(0,datas[i].size):
            datas[i,j] = datas[i,j] / K[i]      #套用矩阵标准化的公式
    return datas 


In [57]:
## 计算得分归一化
def temp3(answer2):
    list_max = np.array([np.max(answer2[0,:]),np.max(answer2[1,:]),np.max(answer2[2,:]),np.max(answer2[3,:])])  #获取每一列的最大值
    list_min = np.array([np.min(answer2[0,:]),np.min(answer2[1,:]),np.min(answer2[2,:]),np.min(answer2[3,:])])  #获取每一列的最小值
    max_list = []       #存放第i个评价对象与最大值的距离
    min_list = []       #存放第i个评价对象与最小值的距离
    answer_list=[]      #存放评价对象的未归一化得分
    for k in range(0,np.size(answer2,axis = 1)):        #遍历每一列数据
        max_sum = 0
        min_sum = 0
        for q in range(0,4):                                #有四个指标
            max_sum += np.power(answer2[q,k]-list_max[q],2)     #按每一列计算Di+
            min_sum += np.power(answer2[q,k]-list_min[q],2)     #按每一列计算Di-
        max_list.append(pow(max_sum,0.5))
        min_list.append(pow(min_sum,0.5))
        answer_list.append(min_list[k]/ (min_list[k] + max_list[k]))    #套用计算得分的公式 Si = (Di-) / ((Di+) +(Di-))
        max_sum = 0
        min_sum = 0
    answer = np.array(answer_list)      #得分归一化
    return (answer / np.sum(answer))


In [32]:
## 主函数
def main():
    # file = 'C:\\Users\\lenovo\Desktop\\数学建模\\TOPSIS法\\第2讲.TOPSIS法（优劣解距离法）7.17\\代码和例题数据\\20条河流的水质情况数据.xlsx'
    # answer1 = read(file)        #读取文件
    answer1 = df
    answer2 = []
    for i in range(0, 4):       #按照不同的列，根据不同的指标转换为极大型指标，因为只有四列
        # answer = None
        # if(i == 0):             #本来就是极大型指标，不用转换
        #     answer = answer1[0]             
        # elif(i == 1):                   #中间型指标
        #     answer = dataDirection_2(answer1[1],7)
        # elif(i==2):                     #极小型指标
        #     answer = dataDirection_1(answer1[2])
        # else:                           #范围型指标
        #     answer = dataDirection_3(answer1[3],10,20)
        # answer2.append(answer)
        
    # answer2 = np.array(answer2)         #将list转换为numpy数组
    # answer3 = temp2(answer2)            #数组正向化
    # answer4 = temp3(answer3)            #标准化处理去钢
    # data = pd.DataFrame(answer4)        #计算得分

    # data.to_csv("HR_topsis.csv",index=False)
    
    
    # #将得分输出到excel表格中
    # writer = pd.ExcelWriter('C:\\Users\\lenovo\Desktop\\数学建模\\TOPSIS法\\第2讲.TOPSIS法（优劣解距离法）7.17\\代码和例题数据\\A.xlsx')		# 写入Excel文件
    # data.to_excel(writer, 'page_1', float_format='%.5f')		# ‘page_1’是写入excel的sheet名
    # writer.save()
    # writer.close()


In [39]:
answer1 = df_res["satisfaction_level"]
answer1

0    0.38
1    0.80
2    0.11
3    0.72
4    0.37
5    0.41
6    0.10
7    0.92
8    0.89
9    0.42
Name: satisfaction_level, dtype: float64

In [40]:
answer2 = []
answer2.append(answer1)
answer2

[0    0.38
 1    0.80
 2    0.11
 3    0.72
 4    0.37
 5    0.41
 6    0.10
 7    0.92
 8    0.89
 9    0.42
 Name: satisfaction_level, dtype: float64]

In [41]:
df_res

satisfaction_level  last_evaluation  number_project  left
0                0.38             0.53               2     1
1                0.80             0.86               5     1
2                0.11             0.88               7     1
3                0.72             0.87               5     1
4                0.37             0.52               2     1
5                0.41             0.50               2     1
6                0.10             0.77               6     1
7                0.92             0.85               5     1
8                0.89             1.00               5     1
9                0.42             0.53               2     1

In [48]:
df_res.columns.values

array(['satisfaction_level', 'last_evaluation', 'number_project', 'left'],
      dtype=object)

In [50]:
answer1 =[]
for i in df_res.columns.values:
    answer1.append(df_res[i])
answer1

[0    0.38
 1    0.80
 2    0.11
 3    0.72
 4    0.37
 5    0.41
 6    0.10
 7    0.92
 8    0.89
 9    0.42
 Name: satisfaction_level, dtype: float64,
 0    0.53
 1    0.86
 2    0.88
 3    0.87
 4    0.52
 5    0.50
 6    0.77
 7    0.85
 8    1.00
 9    0.53
 Name: last_evaluation, dtype: float64,
 0    2
 1    5
 2    7
 3    5
 4    2
 5    2
 6    6
 7    5
 8    5
 9    2
 Name: number_project, dtype: int64,
 0    1
 1    1
 2    1
 3    1
 4    1
 5    1
 6    1
 7    1
 8    1
 9    1
 Name: left, dtype: int64]

In [52]:
len(answer1)

4

In [53]:
answer2 = np.array(answer1)
answer2

array([[0.38, 0.8 , 0.11, 0.72, 0.37, 0.41, 0.1 , 0.92, 0.89, 0.42],
       [0.53, 0.86, 0.88, 0.87, 0.52, 0.5 , 0.77, 0.85, 1.  , 0.53],
       [2.  , 5.  , 7.  , 5.  , 2.  , 2.  , 6.  , 5.  , 5.  , 2.  ],
       [1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ]])

In [55]:
answer3 = temp2(answer2)
answer2

array([[0.20473948, 0.43103048, 0.05926669, 0.38792743, 0.1993516 ,
        0.22090312, 0.05387881, 0.49568505, 0.47952141, 0.226291  ],
       [0.22260853, 0.36121383, 0.36961416, 0.365414  , 0.21840837,
        0.21000804, 0.32341239, 0.35701367, 0.42001609, 0.22260853],
       [0.14106912, 0.35267281, 0.49374193, 0.35267281, 0.14106912,
        0.14106912, 0.42320737, 0.35267281, 0.35267281, 0.14106912],
       [0.31622777, 0.31622777, 0.31622777, 0.31622777, 0.31622777,
        0.31622777, 0.31622777, 0.31622777, 0.31622777, 0.31622777]])

In [59]:
answer4 = temp3(answer3)
answer4

array([0.04832684, 0.15217787, 0.09710703, 0.14424629, 0.04657641,
       0.0523837 , 0.0827465 , 0.15920741, 0.16281389, 0.05441408])

In [61]:
data = pd.DataFrame(answer4)
data

0
0  0.048327
1  0.152178
2  0.097107
3  0.144246
4  0.046576
5  0.052384
6  0.082746
7  0.159207
8  0.162814
9  0.054414